apiVersion: v1
kind: Secret
metadata:
  name: capg-manager-bootstrap-credentials
  namespace: capg-system
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capg-controller-manager
  namespace: capg-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          $patch: delete
        volumeMounts:
        - mountPath: /home/.gcp
          $patch: delete
      volumes:
      - name: credentials
        $patch: delete
